name: CD (production)
on:
  push:
    branches:
      - master

env:
  SITE_URL: https://uitspitss.net
  SLACK_CHANNEL: "#develop"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install
        run: yarn install

      - name: Build
        run: yarn predeploy

      - name: Deploy to staging
        uses: w9jds/firebase-action@master
        if: success()
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        with:
          args: deploy

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: failure() || cancelled()
        with:
          type: ${{ job.status }}
          job_name: "*Deploy to the site*"
          mention: "here"
          mention_if: "failure"
          channel: ${{ env.SLACK_CHANNEL }}
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}

  ping_site:
    needs: deploy
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
      - name: Check the site
        uses: srt32/uptime@master
        with:
          url-to-hit: ${{ env.SITE_URL }}
          expected-statuses: "200,301"

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "*Check the site ${{ env.SITE_URL }} *"
          mention: "here"
          mention_if: "failure"
          channel: ${{ env.SLACK_CHANNEL }}
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
