name: CD (staging)
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - name: Install
        run: yarn install

      - name: Build
        run: yarn predeploy

      - name: Deploy to staging
        uses: w9jds/firebase-action@master
        if: success()
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_STAGING_TOKEN }}
          PROJECT_ID: portfolio-staging-a316b
        with:
          args: deploy

      - name: Slack notification
        uses: 8398a7/action-slack@v2
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: ${{ job.status }}
