name: CD
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        uses: jakejarvis/firebase-deploy-action@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_STAGING_TOKEN }}

  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification
        uses: Ilshidur/action-slack@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          args: "A new commit has been pushed."
